source_editor:

generator:
  metadata:
    markdown: kramdown
    kramdown:
      list_indent: 2

collections_config:
  pages:
    path: src/content/pages
  articles:
    path: src/content/articles

paths:
  static: public
  uploads: public/images

_inputs:
  src:
    type: image