paths:
  uploads: public/images
  static: public
collections_config:
  posts:
    path: src/content/posts
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  site_data:
    path: src/data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: src/pages
    output: true
    url: "/[slug]/"
    icon: notes
    _editables: {}
    _enabled_editors:
      - visual
    _inputs:
      content_blocks:
        empty_type: array
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
_inputs:
  layout:
    type: auto
    hidden: true
    cascade: true
  page_components:
    type: array
    options:
      structures: _structures.content_blocks
  src:
    type: image
    cascade: true
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
