source_editor:

generator:
  metadata:
    markdown: kramdown
    kramdown:
      list_indent: 2

collections_config:
  pages:
    path: src/pages
  posts:
    path: src/content/posts
  site_data:
    path: src/data

paths:
  static: public
  uploads: public/images

_inputs:
  src:
    type: image