collections_config:
  pages:
    path: src/pages
    _enabled_editors:
      - content
      - visual
  posts:
    path: src/content/posts
  site_data:
    path: src/data
paths:
  static: public
  uploads: public/images
_inputs:
  layouts:
    hidden: true
  src:
    type: image