spec:
  structures:
    - content_blocks
  label: My Hero Component
  description: A very simple component
  icon: nature_people

blueprint:
  header: "Hello World!"
  size: 'display-3'
  text: A simple hero unit.

preview:

_inputs: