spec:
  structures:
    - content_blocks
  label: Hero
  description: A very simple component
  icon: nature_people

blueprint:
  header:
    text: About Me
    style: display-3 wvu-shout wvu-bar
  subhead: Subhead goes here.
  content: My cool content.
  image:
    src: /images/greenbrier-valley-carousel.jpeg
    alt: Kids floating on innertubes
  button:
    text: Click Here
    style: btn-primary btn-lg
    href: /my-href

preview:

_inputs: